version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"   # or "daily" / "monthly"
    groups:
      docker:
        patterns:
          - "docker/*"
